package GUIDesignCustomer;

import classFile.*;
import javax.swing.JOptionPane;

public class CustomerProfile extends javax.swing.JPanel {
    private String customerID;
    
    public String getCustomerID() {
        return customerID;
    }

    public void setCustomerID(String customerID) {
        this.customerID = customerID;
        
        String filePath = "src/textFile/customer.txt";
        Customer customer = Customer.readCustomerProfile(customerID);
        
        lblUserID.setText(customer.getUserID());
        lblName.setText(customer.getUsername());
        lblEmail.setText(customer.getEmail());
        lblPhoneNo.setText(customer.getPhoneNumber());
        lblDOB.setText(customer.getDob().toString());
        lblGender.setText(customer.getGender());
    }

    /**
     * Creates new form CustomerProfile
     */
    public CustomerProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlOrderHistory = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel400 = new javax.swing.JLabel();
        jLabel500 = new javax.swing.JLabel();
        jLabel600 = new javax.swing.JLabel();
        pwfOldPassword = new javax.swing.JPasswordField();
        pwfNewPassword = new javax.swing.JPasswordField();
        pwfConfirmPassword = new javax.swing.JPasswordField();
        btnResetPassword = new javax.swing.JButton();
        btnViewOldPw = new javax.swing.JButton();
        btnViewNewPw = new javax.swing.JButton();
        btnViewConfirmPw = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 199, 125));

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Profile");

        pnlOrderHistory.setBackground(new java.awt.Color(255, 157, 0));

        jLabel3.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("UserID:");

        jLabel2.setFont(new java.awt.Font("French Script MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Reset Password");

        jLabel400.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        jLabel400.setForeground(new java.awt.Color(153, 51, 0));
        jLabel400.setText("Old Password:");

        jLabel500.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        jLabel500.setForeground(new java.awt.Color(153, 51, 0));
        jLabel500.setText("New Password:");

        jLabel600.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        jLabel600.setForeground(new java.awt.Color(153, 51, 0));
        jLabel600.setText("Confirm Password:");

        pwfOldPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pwfNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pwfConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnResetPassword.setBackground(new java.awt.Color(252, 231, 196));
        btnResetPassword.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnResetPassword.setForeground(new java.awt.Color(153, 51, 0));
        btnResetPassword.setText("Reset Password");
        btnResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordActionPerformed(evt);
            }
        });

        btnViewOldPw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnViewOldPw.setText("View");
        btnViewOldPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewOldPwMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewOldPwMouseReleased(evt);
            }
        });

        btnViewNewPw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnViewNewPw.setText("View");
        btnViewNewPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewNewPwMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewNewPwMouseReleased(evt);
            }
        });

        btnViewConfirmPw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnViewConfirmPw.setText("View");
        btnViewConfirmPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewConfirmPwMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewConfirmPwMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel600)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(pwfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnViewConfirmPw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetPassword))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel500)
                                .addGap(58, 58, 58)
                                .addComponent(pwfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewNewPw))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel400)
                                .addGap(65, 65, 65)
                                .addComponent(pwfOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewOldPw)))
                        .addGap(233, 233, 233)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewOldPw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwfOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel400)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwfNewPassword)
                    .addComponent(jLabel500)
                    .addComponent(btnViewNewPw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel600)
                    .addComponent(pwfConfirmPassword)
                    .addComponent(btnResetPassword)
                    .addComponent(btnViewConfirmPw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Phone Number:");

        jLabel7.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("DOB:");

        jLabel8.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("Gender:");

        lblUserID.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        lblUserID.setForeground(new java.awt.Color(153, 51, 0));
        lblUserID.setText("lblUserID");

        lblName.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        lblName.setForeground(new java.awt.Color(153, 51, 0));
        lblName.setText("lblName");

        lblEmail.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(153, 51, 0));
        lblEmail.setText("lblEmail");

        lblPhoneNo.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        lblPhoneNo.setForeground(new java.awt.Color(153, 51, 0));
        lblPhoneNo.setText("lblPhoneNo");

        lblDOB.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(153, 51, 0));
        lblDOB.setText("lblDOB");

        lblGender.setFont(new java.awt.Font("STSong", 1, 21)); // NOI18N
        lblGender.setForeground(new java.awt.Color(153, 51, 0));
        lblGender.setText("lblGender");

        javax.swing.GroupLayout pnlOrderHistoryLayout = new javax.swing.GroupLayout(pnlOrderHistory);
        pnlOrderHistory.setLayout(pnlOrderHistoryLayout);
        pnlOrderHistoryLayout.setHorizontalGroup(
            pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlOrderHistoryLayout.createSequentialGroup()
                        .addGroup(pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(66, 66, 66)
                        .addGroup(pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGender)
                            .addComponent(lblDOB)
                            .addComponent(lblPhoneNo)
                            .addComponent(lblEmail)
                            .addComponent(lblName)
                            .addComponent(lblUserID))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlOrderHistoryLayout.setVerticalGroup(
            pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblUserID))
                .addGap(18, 18, 18)
                .addGroup(pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addGroup(pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblPhoneNo))
                .addGap(18, 18, 18)
                .addGroup(pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblDOB))
                .addGap(18, 18, 18)
                .addGroup(pnlOrderHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblGender))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pnlOrderHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewOldPwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewOldPwMousePressed
        pwfOldPassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnViewOldPwMousePressed

    private void btnViewOldPwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewOldPwMouseReleased
        pwfOldPassword.setEchoChar('*');
    }//GEN-LAST:event_btnViewOldPwMouseReleased

    private void btnViewNewPwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewNewPwMousePressed
        pwfNewPassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnViewNewPwMousePressed

    private void btnViewNewPwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewNewPwMouseReleased
        pwfNewPassword.setEchoChar('*');
    }//GEN-LAST:event_btnViewNewPwMouseReleased

    private void btnViewConfirmPwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewConfirmPwMousePressed
        pwfConfirmPassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnViewConfirmPwMousePressed

    private void btnViewConfirmPwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewConfirmPwMouseReleased
        pwfConfirmPassword.setEchoChar('*');
    }//GEN-LAST:event_btnViewConfirmPwMouseReleased

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed
        String filePath = "src/textFile/user.txt";
        FileHandlerImp fileHandlerImp = FileHandlerImp.getFileHandlerImpInstance();
        String line = fileHandlerImp.readFileLine(filePath, customerID);

        if (line == null) {
            JOptionPane.showMessageDialog(null, "User Not Found", "Update Password", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String[] data = line.split(":::");
        String currentPassword = data[2]; // Assuming the password is at index 2

        char[] oldPasswordChars = pwfOldPassword.getPassword();
        char[] newPasswordChars = pwfNewPassword.getPassword();

        String oldPassword = new String(oldPasswordChars);
        String newPassword = new String(newPasswordChars);

        if (currentPassword.equals(oldPassword)) {
            if (newPassword.equals(new String(pwfConfirmPassword.getPassword()))) {
                String updatedLine = line.replace(currentPassword, newPassword);
                if (fileHandlerImp.updateFileLine(filePath, customerID, updatedLine)) {
                    JOptionPane.showMessageDialog(null, "Password Updated Successfully", "Update Password", JOptionPane.PLAIN_MESSAGE);
                    pwfOldPassword.setText("");
                    pwfNewPassword.setText("");
                    pwfConfirmPassword.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to Update Password", "Update Password", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "New Passwords Do Not Match", "Update Password", JOptionPane.WARNING_MESSAGE);
                pwfNewPassword.setText("");
                pwfConfirmPassword.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect Old Password", "Update Password", JOptionPane.WARNING_MESSAGE);
            pwfOldPassword.setText("");
        }
    }//GEN-LAST:event_btnResetPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JButton btnViewConfirmPw;
    private javax.swing.JButton btnViewNewPw;
    private javax.swing.JButton btnViewOldPw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel400;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel500;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel600;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JPanel pnlOrderHistory;
    private javax.swing.JPasswordField pwfConfirmPassword;
    private javax.swing.JPasswordField pwfNewPassword;
    private javax.swing.JPasswordField pwfOldPassword;
    // End of variables declaration//GEN-END:variables
}
