package GUIDesignCustomer;

import classFile.*;
import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CustomerDashboard extends javax.swing.JPanel {
    private String customerID;
    private Customer customer;

    public String getCustomerID() {
        return customerID;
    }

    public void setCustomerID(String customerID) {
        this.customerID = customerID;
        customer = Customer.readCustomerProfile(customerID);
        String filePath = "src/textFile/customer.txt";

        lblCustomerID.setText(customerID);
        updateBalanceLabel(customer);

        addToTable();
    }
    
    public void updateBalanceLabel(Customer customer) {
        DecimalFormat df = new DecimalFormat("#.00");
        lblBalance.setText(df.format((double) customer.getBalance()));
    }
    
    public void addToTable() {
        List<String[]> dataList = Order.readOrderStatus(customerID);

        if (dataList.isEmpty()) {
            return;
        }

        String[] columns = dataList.get(0);

        DefaultTableModel model = (DefaultTableModel) tblOrderStatus.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);

        for (String column : columns) {
            model.addColumn(column);
        }

        for (int i = 1; i < dataList.size(); i++) {
            String[] data = dataList.get(i);
            String[] row = {data[0], Order.orderStatus[Integer.parseInt(data[data.length - 1])]};
            if (row != null && row.length > 0 && !isRowEmpty(row)) {
                model.addRow(row);
            }
        }
    }

    private void deleteRow() {
        DefaultTableModel model = (DefaultTableModel) tblOrderStatus.getModel();
        int selectedRow = tblOrderStatus.getSelectedRow();

        if (selectedRow != -1) {
            model.removeRow(selectedRow);
        }
    }

    // Helper method to check if a row is empty
    private boolean isRowEmpty(String[] row) {
        for (String cell : row) {
            if (cell != null && !cell.trim().isEmpty()) {
                return false; // If any cell is non-empty, the row is not empty
            }
        }
        return true; // If all cells are empty, the row is empty
    }

    /**
     * Creates new form Dashboard
     */
    public CustomerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        btnRequestTopUp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderStatus = new javax.swing.JTable();
        btnCancelOrder = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 199, 125));

        jPanel1.setBackground(new java.awt.Color(255, 157, 0));

        jLabel2.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("CustomerID:");

        jLabel3.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Balance (RM):");

        lblCustomerID.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        lblCustomerID.setForeground(new java.awt.Color(153, 51, 0));
        lblCustomerID.setText("lblCustomerID");

        lblBalance.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(153, 51, 0));
        lblBalance.setText("lblBalance");

        btnRequestTopUp.setBackground(new java.awt.Color(252, 231, 196));
        btnRequestTopUp.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnRequestTopUp.setForeground(new java.awt.Color(153, 51, 0));
        btnRequestTopUp.setText("Request Top Up");
        btnRequestTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTopUpActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("French Script MT", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("Order Status:");

        tblOrderStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                // Your data rows here
            },
            new String [] {
                // Your column names here
            }
        ) {
            // Make all cells non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // This ensures no cell can be edited
            }
        });
        jScrollPane1.setViewportView(tblOrderStatus);

        btnCancelOrder.setBackground(new java.awt.Color(252, 231, 196));
        btnCancelOrder.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCancelOrder.setForeground(new java.awt.Color(153, 51, 0));
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        btnOK.setBackground(new java.awt.Color(252, 231, 196));
        btnOK.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnOK.setForeground(new java.awt.Color(153, 51, 0));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel5))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRequestTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCustomerID))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCustomerID))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblBalance)
                    .addComponent(btnRequestTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("French Script MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestTopUpActionPerformed
        new CustomerRequestTopUp(customerID).setVisible(true);
    }//GEN-LAST:event_btnRequestTopUpActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "Are you sure to cancel the order?", "Cancel Order", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (input == JOptionPane.YES_OPTION){
            DefaultTableModel model = (DefaultTableModel) tblOrderStatus.getModel();
            int selectedRow = tblOrderStatus.getSelectedRow();

            if (selectedRow != -1) {
                String orderID = (String) model.getValueAt(selectedRow, 0);
                boolean flag = Order.cancelOrder(orderID);
                if (flag){
                    this.customer = Customer.readCustomerProfile(customerID);
                    
                    DecimalFormat df = new DecimalFormat("#.00");
                    lblBalance.setText(df.format(customer.getBalance()));
                    deleteRow();
                }
            }
        }
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblOrderStatus.getModel();
        int selectedRow = tblOrderStatus.getSelectedRow();

        if (selectedRow != -1) {
            String orderID = (String) model.getValueAt(selectedRow, 0);
            FileHandlerImp fileHandlerImp = FileHandlerImp.getFileHandlerImpInstance();
            String line = fileHandlerImp.readFileLine("src/textFile/order.txt", orderID);

            int flag = Order.deleteOrder(orderID);
            if (flag != -1) {
                deleteRow();
            }
            if (flag == Order.DONE){
                fileHandlerImp.writeFileNewLine("src/textFile/orderHistory.txt", line);
            } else if (flag == Order.REJECT) {
                Order.orderRejected(line, customerID);
                this.customer = Customer.readCustomerProfile(customerID);

                DecimalFormat df = new DecimalFormat("#.00");
                lblBalance.setText(df.format(customer.getBalance()));
            }
        }
    }//GEN-LAST:event_btnOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRequestTopUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JTable tblOrderStatus;
    // End of variables declaration//GEN-END:variables
}
