package GUIDesignAdmin;

import classFile.Admin;
import classFile.Runner;
import classFile.Vendor;
import classFile.Customer;
import classFile.User;
import classFile.FileHandlerImp;
import classFile.AdminUtil;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class EditUserDetails extends javax.swing.JPanel {

    public EditUserDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        cbRole = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtDOBYear = new javax.swing.JTextField();
        txtDOBMonth = new javax.swing.JTextField();
        txtDOBDay = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(518, 349));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Edit User Details");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("UserID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Role:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phone Number:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("DOB:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("-");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("-");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Gender");

        txtUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserIDKeyPressed(evt);
            }
        });

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "customer", "vendor", "runner" }));

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyPressed(evt);
            }
        });

        txtDOBYear.setForeground(java.awt.Color.lightGray);
        txtDOBYear.setText("yyyy");
        txtDOBYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDOBYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDOBYearFocusLost(evt);
            }
        });
        txtDOBYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDOBYearKeyPressed(evt);
            }
        });

        txtDOBMonth.setForeground(java.awt.Color.lightGray);
        txtDOBMonth.setText("MM");
        txtDOBMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDOBMonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDOBMonthFocusLost(evt);
            }
        });
        txtDOBMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDOBMonthKeyPressed(evt);
            }
        });

        txtDOBDay.setForeground(java.awt.Color.lightGray);
        txtDOBDay.setText("dd");
        txtDOBDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDOBDayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDOBDayFocusLost(evt);
            }
        });
        txtDOBDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDOBDayKeyPressed(evt);
            }
        });

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addComponent(btnRegister)
                            .addComponent(btnDelete)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(75, 75, 75)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(txtName))
                                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtDOBYear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtDOBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtDOBDay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPhoneNumber))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDOBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOBDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private User createRoleInstance(String role) {
        User u = null;
        switch (role) {
            case "customer":
                u = new Customer();
                break;
            case "vendor":
                u = new Vendor();
                break;
            case "runner":
                u = new Runner();
                break;
            default:
                break;
        }
        return u;
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        User u = null;
        String userID = txtUserID.getText();
        FileHandlerImp fileHandlerImp = FileHandlerImp.getFileHandlerImpInstance();
        String filePath = "src/textFile/user.txt";
        String line = fileHandlerImp.readFileLine(filePath, userID);
        if (line == null) {
            return;
        }
        String[] data = line.split(":::"); //0-id, 1-name, 2-pw, 3-email, 4-phone.no, 5-dob, 6-gender, 7-role
        //Determine the role of the user
        System.out.println(data[7].trim());
        u = createRoleInstance(data[7].trim());

        //Setting the value of the user
        //id
        u.setUserID(userID);
        //name
        String username = txtName.getText();
        if (username.isEmpty()) {
            u.setUsername(data[1]);
        } else if (AdminUtil.isUsername(username)) {
            u.setUsername(username);
        } else {
            txtName.setText("");
            JOptionPane.showMessageDialog(null, "Username Must Be All Alphabets");
        }
        //password
        u.setPassword(data[2]);
        // email
        String email = txtEmail.getText();
        if (email.isEmpty()) {
            u.setEmail(data[3]);
        } else if (AdminUtil.isEmail(email)) {
            u.setEmail(email);
        } else {
            txtEmail.setText("");
            JOptionPane.showMessageDialog(null, "Email Format Is Invalid");
        }
        // phone number
        String phoneNumber = txtPhoneNumber.getText();
        if (phoneNumber.isEmpty()) {
            u.setPhoneNumber(data[4]);
        } else if (AdminUtil.isPhoneNumber(phoneNumber)) {
            u.setPhoneNumber(phoneNumber);
        } else {
            txtPhoneNumber.setText("");
            JOptionPane.showMessageDialog(null, "Phone Number Format Invalid");
        }
        //dob
        String year = txtDOBYear.getText();
        String month = txtDOBMonth.getText();
        String day = txtDOBDay.getText();
        String dobStr = year + "-" + month + "-" + day;
        boolean isFilledYear = !year.equals("yyyy");
        boolean isFilledMonth = !month.equals("MM");
        boolean isFilledDay = !day.equals("dd");
        if (!isFilledYear && !isFilledMonth && !isFilledDay) {
            u.setDob(data[5]);
        } else {
            if (isFilledYear && isFilledMonth && isFilledDay) {
                if (AdminUtil.isDOB(dobStr)) {
                    u.setDob(dobStr);
                } else {
                    JOptionPane.showMessageDialog(null, "DOB Format Is Invalid");
                }
            } else {
                JOptionPane.showMessageDialog(null, "All the Columns of the DOB Components Must Be Filled");
            }
        }
        //gender
        u.setGender(data[6]);
        //role
        u.setRole(data[7]);

        //validate
        if (txtUserID.getText().startsWith("c")) {
            if (cbRole.getSelectedItem().toString().equals("customer")) {
                Customer customer = Customer.readCustomerProfile(userID);
                Customer c = (Customer) u;
                c.setBalance(customer.getBalance());
                admin.update(c);
            } else {
                JOptionPane.showMessageDialog(null, "Wrong role");
                return;
            }
        } else if (txtUserID.getText().startsWith("r")) {
            if (cbRole.getSelectedItem().toString().equals("runner")) {
                Runner runner = Runner.readRunnerProfile(userID);
                Runner r = (Runner) u;
                r.setWorkStatus(runner.getWorkStatus());
                admin.update(r);
            } else {
                JOptionPane.showMessageDialog(null, "Wrong role");
                return;
            }
        } else if (txtUserID.getText().startsWith("v")) {
            if (cbRole.getSelectedItem().toString().equals("vendor")) {
                Vendor v = (Vendor) u;
                admin.update(v);
            } else {
                JOptionPane.showMessageDialog(null, "Wrong role");
                return;
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // Assuming you have validation methods and user creation logic in place
        String role = cbRole.getSelectedItem().toString();
        String userID = AdminUtil.generateID(role); // Generate new user ID
        String username = txtName.getText();
        String email = txtEmail.getText();
        String phoneNumber = txtPhoneNumber.getText();
        String dobStr = txtDOBYear.getText() + "-" + txtDOBMonth.getText() + "-" + txtDOBDay.getText();
        String gender = (String) cbGender.getSelectedItem();

        // Validate inputs
        if (!AdminUtil.isUsername(username)) {
            JOptionPane.showMessageDialog(null, "Invalid Username");
            return;
        }
        if (!AdminUtil.isEmail(email)) {
            JOptionPane.showMessageDialog(null, "Invalid Email Format");
            return;
        }
        if (!AdminUtil.isPhoneNumber(phoneNumber)) {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number");
            return;
        }
        if (!AdminUtil.isDOB(dobStr)) {
            JOptionPane.showMessageDialog(null, "Invalid Date of Birth");
            return;
        }

        // Create and set User object
        User newUser = createRoleInstance(role);
        newUser.setRole(role);
        newUser.setUserID(userID);
        newUser.setUsername(username);
        newUser.setEmail(email);
        newUser.setPhoneNumber(phoneNumber);
        newUser.setDob(dobStr);
        newUser.setGender(gender);

        admin.register(newUser);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String userID = txtUserID.getText();
        if (userID.isEmpty() || !AdminUtil.isId(userID)) {
            JOptionPane.showMessageDialog(null, "Invalid UserID");
            return;
        }

        admin.delete(userID);
        if (userID != null && userID.matches("v\\d{6}")) {
            admin.dltstorename(userID);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtUserIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIDKeyPressed
        int len = txtUserID.getText().length();
        if (len > 7 && evt.getExtendedKeyCode() != KeyEvent.VK_BACK_SPACE) {
            txtUserID.setEditable(false);
            return;
        }
        txtUserID.setEditable(true);
    }//GEN-LAST:event_txtUserIDKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtPhoneNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyPressed
        int len = txtPhoneNumber.getText().length();
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            if (len < 11) {
                txtPhoneNumber.setEditable(true);
            } else {
                txtPhoneNumber.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtPhoneNumber.setEditable(true);
            } else {
                txtPhoneNumber.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtPhoneNumberKeyPressed

    private void txtDOBYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBYearFocusGained
        if (txtDOBYear.getText().equals("yyyy")) {
            txtDOBYear.setText("");
            txtDOBYear.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDOBYearFocusGained

    private void txtDOBYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBYearKeyPressed
        int len = txtDOBYear.getText().length();
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            if (len < 4) {
                txtDOBYear.setEditable(true);
            } else {
                txtDOBYear.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtDOBYear.setEditable(true);
            } else {
                txtDOBYear.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtDOBYearKeyPressed

    private void txtDOBMonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBMonthFocusGained
        if (txtDOBMonth.getText().equals("MM")) {
            txtDOBMonth.setText("");
            txtDOBMonth.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDOBMonthFocusGained

    private void txtDOBMonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBMonthKeyPressed
        int len = txtDOBMonth.getText().length();
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            if (len < 2) {
                txtDOBMonth.setEditable(true);
            } else {
                txtDOBMonth.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtDOBMonth.setEditable(true);
            } else {
                txtDOBMonth.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtDOBMonthKeyPressed

    private void txtDOBDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBDayFocusGained
        if (txtDOBDay.getText().equals("dd")) {
            txtDOBDay.setText("");
            txtDOBDay.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDOBDayFocusGained

    private void txtDOBDayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBDayKeyPressed
        int len = txtDOBDay.getText().length();
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            if (len < 2) {
                txtDOBDay.setEditable(true);
            } else {
                txtDOBDay.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtDOBDay.setEditable(true);
            } else {
                txtDOBDay.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtDOBDayKeyPressed

    private void txtDOBYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBYearFocusLost
        if (txtDOBYear.getText().equals("")) {
            txtDOBYear.setText("yyyy");
            txtDOBYear.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtDOBYearFocusLost

    private void txtDOBMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBMonthFocusLost
        if (txtDOBMonth.getText().equals("")) {
            txtDOBMonth.setText("MM");
            txtDOBMonth.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtDOBMonthFocusLost

    private void txtDOBDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBDayFocusLost
        if (txtDOBDay.getText().equals("")) {
            txtDOBDay.setText("MM");
            txtDOBDay.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtDOBDayFocusLost

    private Admin admin = new Admin();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDOBDay;
    private javax.swing.JTextField txtDOBMonth;
    private javax.swing.JTextField txtDOBYear;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
