package GUIDesignAdmin;

import classFile.Admin;
import classFile.FileHandlerImp;
import classFile.AdminUtil;
import java.awt.event.KeyEvent;
import java.util.StringJoiner;
import javax.swing.*;

public class Profile extends javax.swing.JPanel {
    private String adminID;
    
    public String getAdminID() {
        return adminID;
    }

    public void setAdminID(String adminID) {
        this.adminID = adminID;
        
        String filePath = "src/textFile/admin.txt";
        Admin admin = Admin.readAdminProfile(adminID);
        
        
        lblUserID.setText(admin.getUserID());
        txtUserName.setText(admin.getUsername());
        txtEmail.setText(admin.getEmail());
        txtPhoneNumber.setText(admin.getPhoneNumber());
        
        String dobStr = admin.getDob().toString();
        String[] dobArr = dobStr.split("-");
        txtDOBYear.setText(dobArr[0]);
        txtDOBMonth.setText(dobArr[1]);
        txtDOBDay.setText(dobArr[2]); 
        
        lblGender.setText(admin.getGender());
    }
    
    /**
     * Creates new form Home
     */
    public Profile() {
        initComponents();  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        panelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelUserDetails = new javax.swing.JPanel();
        pnlResetPassword = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pwdNewPassword = new javax.swing.JPasswordField();
        pwdOldPassword = new javax.swing.JPasswordField();
        pwdConfirmPassword = new javax.swing.JPasswordField();
        btnUpdatePassword = new javax.swing.JButton();
        btnViewOldPassword = new javax.swing.JButton();
        btnViewConfirmPassword = new javax.swing.JButton();
        btnViewNewPassword = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDOBYear = new javax.swing.JTextField();
        txtDOBMonth = new javax.swing.JTextField();
        txtDOBDay = new javax.swing.JTextField();
        btnUpdateProfile1 = new javax.swing.JButton();
        lblGender = new javax.swing.JLabel();

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setForeground(new java.awt.Color(255, 255, 255));
        panelMain.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Profile");

        panelUserDetails.setBackground(new java.awt.Color(231, 230, 230));
        panelUserDetails.setForeground(new java.awt.Color(153, 153, 153));

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel.setText("Reset Password:");

        jLabel11.setText("Old Password:");

        jLabel12.setText("New Password:");

        jLabel13.setText("Confirm Password:");

        btnUpdatePassword.setText("UpdatePW");
        btnUpdatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePasswordActionPerformed(evt);
            }
        });

        btnViewOldPassword.setText("View");
        btnViewOldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewOldPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewOldPasswordMouseReleased(evt);
            }
        });

        btnViewConfirmPassword.setText("View");
        btnViewConfirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewConfirmPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewConfirmPasswordMouseReleased(evt);
            }
        });

        btnViewNewPassword.setText("View");
        btnViewNewPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewNewPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewNewPasswordMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlResetPasswordLayout = new javax.swing.GroupLayout(pnlResetPassword);
        pnlResetPassword.setLayout(pnlResetPasswordLayout);
        pnlResetPasswordLayout.setHorizontalGroup(
            pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResetPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel)
                    .addGroup(pnlResetPasswordLayout.createSequentialGroup()
                        .addGroup(pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(35, 35, 35)
                        .addGroup(pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwdConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(pwdOldPassword)
                            .addComponent(pwdNewPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlResetPasswordLayout.createSequentialGroup()
                                .addGroup(pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViewOldPassword)
                                    .addComponent(btnViewNewPassword))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlResetPasswordLayout.createSequentialGroup()
                                .addComponent(btnViewConfirmPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdatePassword)))))
                .addContainerGap())
        );
        pnlResetPasswordLayout.setVerticalGroup(
            pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResetPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pwdOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewOldPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pwdNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewNewPassword))
                .addGap(11, 11, 11)
                .addGroup(pnlResetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pwdConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewConfirmPassword)
                    .addComponent(btnUpdatePassword))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("UserID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phone Number:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("DOB:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("-");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("-");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Gender");

        lblUserID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserID.setText("lblUserID");

        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyPressed(evt);
            }
        });

        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });

        txtDOBYear.setText("yyyy");
        txtDOBYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDOBYearFocusGained(evt);
            }
        });
        txtDOBYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDOBYearKeyPressed(evt);
            }
        });

        txtDOBMonth.setText("mm");
        txtDOBMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDOBMonthFocusGained(evt);
            }
        });
        txtDOBMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDOBMonthKeyPressed(evt);
            }
        });

        txtDOBDay.setText("dd");
        txtDOBDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDOBDayFocusGained(evt);
            }
        });
        txtDOBDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDOBDayKeyPressed(evt);
            }
        });

        btnUpdateProfile1.setText("Update");
        btnUpdateProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfile1ActionPerformed(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGender.setText("lblGender");

        javax.swing.GroupLayout panelUserDetailsLayout = new javax.swing.GroupLayout(panelUserDetails);
        panelUserDetails.setLayout(panelUserDetailsLayout);
        panelUserDetailsLayout.setHorizontalGroup(
            panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResetPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelUserDetailsLayout.createSequentialGroup()
                        .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15))
                        .addGap(35, 35, 35)
                        .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserDetailsLayout.createSequentialGroup()
                                .addComponent(lblUserID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateProfile1)
                                .addGap(9, 9, 9))
                            .addGroup(panelUserDetailsLayout.createSequentialGroup()
                                .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGender)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelUserDetailsLayout.createSequentialGroup()
                                        .addComponent(txtDOBYear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtDOBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtDOBDay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 54, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelUserDetailsLayout.setVerticalGroup(
            panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserDetailsLayout.createSequentialGroup()
                .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdateProfile1)
                    .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblUserID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDOBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDOBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDOBDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(lblGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResetPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                        .addComponent(panelUserDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUserDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfile1ActionPerformed
        // TODO add your handling code here:
        Admin admin = Admin.readAdminProfile(adminID);
        //userID
        admin.setUserID(lblUserID.getText());
        //username
        admin.setUsername(txtUserName.getText());
        //email
        if (!AdminUtil.isEmail(txtEmail.getText())) {
            JOptionPane.showMessageDialog(null, "Email Format Error!");
            return;
        }
        admin.setEmail(txtEmail.getText());
        //phone number
        if (!AdminUtil.isPhoneNumber(txtPhoneNumber.getText())) {
            JOptionPane.showMessageDialog(null, "Phone Number Format Error!");
            return;
        }
        admin.setPhoneNumber(txtPhoneNumber.getText());
        //dob
        StringJoiner dobSj = new StringJoiner("-");
        String dobStr = dobSj.add(txtDOBYear.getText()).add(txtDOBMonth.getText()).add(txtDOBDay.getText()).toString();
        if (!AdminUtil.isDOB(dobStr)) {
            JOptionPane.showMessageDialog(null, "DOB Format Error!");
            return;
        }
        admin.setDob(dobStr);
        //gender
        admin.setGender(lblGender.getText());
        //save to file
        admin.update(admin);
    }//GEN-LAST:event_btnUpdateProfile1ActionPerformed

    private void btnViewOldPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewOldPasswordMousePressed
        pwdOldPassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnViewOldPasswordMousePressed

    private void btnViewOldPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewOldPasswordMouseReleased
        pwdOldPassword.setEchoChar('*');
    }//GEN-LAST:event_btnViewOldPasswordMouseReleased

    private void btnViewNewPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewNewPasswordMousePressed
        pwdNewPassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnViewNewPasswordMousePressed

    private void btnViewNewPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewNewPasswordMouseReleased
        pwdNewPassword.setEchoChar('*');
    }//GEN-LAST:event_btnViewNewPasswordMouseReleased

    private void btnViewConfirmPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewConfirmPasswordMousePressed
        pwdConfirmPassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnViewConfirmPasswordMousePressed

    private void btnViewConfirmPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewConfirmPasswordMouseReleased
        pwdConfirmPassword.setEchoChar('*');
    }//GEN-LAST:event_btnViewConfirmPasswordMouseReleased

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        char c = evt.getKeyChar();
    
        if (Character.isDigit(c)) {
            evt.consume();
            txtUserName.setEditable(false);
        } else {
            if (Character.isAlphabetic(c) || Character.isWhitespace(c)) {
                txtUserName.setEditable(true);
            } else {
                if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                    txtUserName.setEditable(true);
                } else {
                    txtUserName.setEditable(false);
                }
            }
        }
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void txtPhoneNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyPressed
        String phoneNumber = txtPhoneNumber.getText();
        int len = phoneNumber.length();
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            if (len < 11) {
                txtPhoneNumber.setEditable(true);
            } else {
                txtPhoneNumber.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtPhoneNumber.setEditable(true);
            } else {
                txtPhoneNumber.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtPhoneNumberKeyPressed

    private void txtDOBYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBYearKeyPressed
        String year = txtDOBYear.getText();
        int len = year.length();
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            if (len < 4) {
                txtDOBYear.setEditable(true);
            } else {
                txtDOBYear.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtDOBYear.setEditable(true);
            } else {
                txtDOBYear.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtDOBYearKeyPressed

    private void txtDOBMonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBMonthKeyPressed
        String month = txtDOBMonth.getText();
        int len = month.length();
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            if (len < 2) {
                txtDOBMonth.setEditable(true);
            } else {
                txtDOBMonth.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtDOBMonth.setEditable(true);
            } else {
                txtDOBMonth.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtDOBMonthKeyPressed

    private void txtDOBDayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBDayKeyPressed
        String day = txtDOBDay.getText();
        int len = day.length();
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            if (len < 2) {
                txtDOBDay.setEditable(true);
            } else {
                txtDOBDay.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtDOBDay.setEditable(true);
            } else {
                txtDOBDay.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtDOBDayKeyPressed

    private void txtDOBYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBYearFocusGained
        if (txtDOBYear.getText().equals("yyyy")) {
            txtDOBYear.setText("");
        }
    }//GEN-LAST:event_txtDOBYearFocusGained

    private void txtDOBMonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBMonthFocusGained
        if (txtDOBMonth.getText().equals("yyyy")) {
            txtDOBMonth.setText("");
        }
    }//GEN-LAST:event_txtDOBMonthFocusGained

    private void txtDOBDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOBDayFocusGained
        if (txtDOBDay.getText().equals("yyyy")) {
            txtDOBDay.setText("");
        }
    }//GEN-LAST:event_txtDOBDayFocusGained

    private void btnUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePasswordActionPerformed
        String filePath = "src/textFile/user.txt";
        FileHandlerImp fileHandlerImp = FileHandlerImp.getFileHandlerImpInstance();
        String line = fileHandlerImp.readFileLine(filePath, adminID);

        if (line == null) {
            JOptionPane.showMessageDialog(null, "User Not Found", "Update Password", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String[] data = line.split(":::");
        String currentPassword = data[2]; // Assuming the password is at index 2

        char[] oldPasswordChars = pwdOldPassword.getPassword();
        char[] newPasswordChars = pwdNewPassword.getPassword();

        String oldPassword = new String(oldPasswordChars);
        String newPassword = new String(newPasswordChars);

        if (currentPassword.equals(oldPassword)) {
            if (newPassword.equals(new String(pwdConfirmPassword.getPassword()))) {
                String updatedLine = line.replace(currentPassword, newPassword);
                if (fileHandlerImp.updateFileLine(filePath, adminID, updatedLine)) {
                    JOptionPane.showMessageDialog(null, "Password Updated Successfully", "Update Password", JOptionPane.PLAIN_MESSAGE);
                    pwdOldPassword.setText("");
                    pwdNewPassword.setText("");
                    pwdConfirmPassword.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to Update Password", "Update Password", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "New Passwords Do Not Match", "Update Password", JOptionPane.WARNING_MESSAGE);
                pwdNewPassword.setText("");
                pwdConfirmPassword.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect Old Password", "Update Password", JOptionPane.WARNING_MESSAGE);
            pwdOldPassword.setText("");
        }
    }//GEN-LAST:event_btnUpdatePasswordActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdatePassword;
    private javax.swing.JButton btnUpdateProfile1;
    private javax.swing.JButton btnViewConfirmPassword;
    private javax.swing.JButton btnViewNewPassword;
    private javax.swing.JButton btnViewOldPassword;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelUserDetails;
    private javax.swing.JPanel pnlResetPassword;
    private javax.swing.JPasswordField pwdConfirmPassword;
    private javax.swing.JPasswordField pwdNewPassword;
    private javax.swing.JPasswordField pwdOldPassword;
    private javax.swing.JTextField txtDOBDay;
    private javax.swing.JTextField txtDOBMonth;
    private javax.swing.JTextField txtDOBYear;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
