package GUIDesignAdmin;

import classFile.Admin;
import classFile.Notification;
import classFile.FileHandlerImp;
import classFile.Transaction;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

public class TopUp extends javax.swing.JPanel {
    private Admin admin;
    private String adminID;
    private Transaction transaction;
    
    public String getAdminID() {
        return adminID;
    }

    public void setAdminID(String adminID) {
        this.adminID = adminID;
        
        admin = Admin.readAdminProfile(adminID);
        admin.setUserID(adminID);
        transaction = null;
    }
    
    public TopUp() {
        initComponents();
    }
    
    private boolean exceedsLimit(String text) {
        try {
            double amount = Double.parseDouble(text) / 100;
            return amount > 1000.00;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private String formatText(String text) {
        while (text.length() < 3) {
            text = "0" + text;
        }
        return text.substring(0, text.length() - 2) + "." + text.substring(text.length() - 2);
    }

    private String removeLeadingZeros(String text) {
        while (text.length() > 1 && text.startsWith("0")) {
            text = text.substring(1);
        }
        return text;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtUserID = new javax.swing.JTextField();
        btnTopUp = new javax.swing.JButton();
        btnViewTopUpRequest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTransactionID = new javax.swing.JTextField();
        btnGenerateReceipt = new javax.swing.JButton();
        btnSendReceipt = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(518, 349));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setText("Top-Up");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("UserID (CustomerID):");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setText("Top-Up Details");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Amount (RM):");

        txtAmount.setForeground(java.awt.Color.lightGray);
        txtAmount.setText("Maximum RM 1000 in a single top-up");
        txtAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAmountFocusLost(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        txtUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserIDKeyPressed(evt);
            }
        });

        btnTopUp.setText("Top-Up & Send Receipt");
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });

        btnViewTopUpRequest.setText("View Top-Up Request");
        btnViewTopUpRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTopUpRequestActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setText("Generate Receipt");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("TransactionID:");

        btnGenerateReceipt.setText("Generate Receipt");
        btnGenerateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReceiptActionPerformed(evt);
            }
        });

        btnSendReceipt.setText("Send");
        btnSendReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtTransactionID, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendReceipt)
                            .addComponent(btnGenerateReceipt))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTransactionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateReceipt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendReceipt)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTopUp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewTopUpRequest, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAmount)
                                    .addComponent(txtUserID))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnViewTopUpRequest)
                .addGap(12, 12, 12)
                .addComponent(btnTopUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountFocusGained
        if (txtAmount.getText().equals("Maximum RM 1000 in a single top-up")) {
            txtAmount.setText("0.00");
            txtAmount.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtAmountFocusGained

    private void txtAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountFocusLost
        if (txtAmount.getText().equals("0.00")) {
            txtAmount.setText("Maximum RM 1000 in a single top-up");
            txtAmount.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtAmountFocusLost

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        char c = evt.getKeyChar();
        String currentText = txtAmount.getText().replaceAll("\\.", "");

        // Check for digit input
        if (Character.isDigit(c)) {
            // Remove leading zeros before adding a new digit
            currentText = removeLeadingZeros(currentText);
            String potentialText = currentText + c;        
            if (exceedsLimit(potentialText)) {
                evt.consume();
                return;
            }
            txtAmount.setText(formatText(potentialText));
            evt.consume();
        }
        // Handle backspace
        if (c == KeyEvent.VK_BACK_SPACE) {
            if (!currentText.equals("000")) {
                txtAmount.setText(formatText(currentText.substring(0, currentText.length() - 1)));
            }
            evt.consume();
        }
    }//GEN-LAST:event_txtAmountKeyTyped

    private void txtUserIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIDKeyPressed
        int len = txtUserID.getText().length();
        if (len <=  7) {
            txtUserID.setEditable(true);
        } else {
            if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) {
                txtUserID.setEditable(true);
            }
            else {
                txtUserID.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtUserIDKeyPressed

    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpActionPerformed
        if (!txtAmount.getText().equals("Maximum RM 1000 in a single top-up")) {
            String userID = txtUserID.getText();
            String topUpAmountStr = txtAmount.getText();
            double topUpAmount = Double.parseDouble(topUpAmountStr);
            FileHandlerImp fileHandlerImp = FileHandlerImp.getFileHandlerImpInstance();
            //user not exists
            if (fileHandlerImp.readFileLine("src/textFile/customer.txt", userID) == null) {
                JOptionPane.showMessageDialog(null, "Customer (id:" + userID + ") Not Found");
                return;
            }
            admin.topUp(userID, topUpAmount);
        } else {
            JOptionPane.showMessageDialog(null, "Please enter the top- up amount");
        }
    }//GEN-LAST:event_btnTopUpActionPerformed

    private void btnViewTopUpRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTopUpRequestActionPerformed
        Notification.readNotificationBriefs("src/textFile/notification.txt", adminID);
    }//GEN-LAST:event_btnViewTopUpRequestActionPerformed

    private void btnGenerateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReceiptActionPerformed
        transaction = null;
        String transactionID = txtTransactionID.getText();
        FileHandlerImp fileHandlerImp = FileHandlerImp.getFileHandlerImpInstance();
        String line = fileHandlerImp.readFileLine("src/textFile/transaction.txt", transactionID);
        if(line.equals("false")) {
            JOptionPane.showMessageDialog(null, "TransactionID Wrong", "Warning(Transaction)", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String[] transactionData = line.split(":::");
        String senderID = transactionData[1];
        String receiverID = transactionData[2];
        double amount = Double.parseDouble(transactionData[3]);
        String time = transactionData[4];
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime ldt = LocalDateTime.parse(time, formatter);
        
        String description = transactionData[5];

        transaction = new Transaction(transactionID, senderID, receiverID, amount, ldt, description);

        String receiptStr = transaction.getReceipt();
        
        String title = "Receipt";
        String message = receiptStr.replace("<newline>", "\n");
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnGenerateReceiptActionPerformed

    private void btnSendReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReceiptActionPerformed
        if (transaction == null) {
            JOptionPane.showMessageDialog(null, "TransactionID Wrong", "Warning(Transaction)", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Notification notification = new Notification(adminID, transaction.getSenderID(), "Receipt (" + transaction.getTransactionID() + ")", transaction.getReceipt());
        Notification.sendNotification(notification, "notification.txt");
        txtTransactionID.setText("");
    }//GEN-LAST:event_btnSendReceiptActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReceipt;
    private javax.swing.JButton btnSendReceipt;
    private javax.swing.JButton btnTopUp;
    private javax.swing.JButton btnViewTopUpRequest;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtTransactionID;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
