package GUIDesignAdmin;

import classFile.Admin;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class View extends javax.swing.JPanel {
    private Admin admin = new Admin();
    private DefaultTableModel originalTableModel;

    /**
     * Creates new form temp
     */
    public View() {
        initComponents();
        originalTableModel = (DefaultTableModel) tblReadUser.getModel();
    }
    
    private void addToTable(String role) {
        List<String[]> dataList = admin.readUsers(role);
        
        if(dataList.isEmpty()) {
            return;
        }
        
        String[] columns = dataList.get(0);
        
        DefaultTableModel model = (DefaultTableModel)tblReadUser.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        
        for (String column : columns) {
            model.addColumn(column);
        }
        
        for (int i = 1; i < dataList.size(); i++) {
            String[] row = dataList.get(i);
            if (row != null && row.length > 0 && !isRowEmpty(row)) {
                model.addRow(row);
            }
        }
    }
    
    // Helper method to check if a row is empty
    private boolean isRowEmpty(String[] row) {
        for (String cell : row) {
            if (cell != null && !cell.trim().isEmpty()) {
                return false; // If any cell is non-empty, the row is not empty
            }
        }
        return true; // If all cells are empty, the row is empty
    }
    
    private void resetTable() {
        tblReadUser.setModel(originalTableModel);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(originalTableModel);
        tblReadUser.setRowSorter(sorter);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReadUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchUserID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnVendor = new javax.swing.JButton();
        btnRunner = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblReadUser.setBackground(new java.awt.Color(204, 204, 204));
        tblReadUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                // Your data rows here
            },
            new String [] {
                // Your column names here
            }
        ) {
            // Make all cells non-editable
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // This ensures no cell can be edited
            }
        }
    );
    tblReadUser.setToolTipText("");
    jScrollPane1.setViewportView(tblReadUser);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
    jLabel1.setText("View User");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel2.setText("UserID:");

    btnSearch.setText("Search");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSearchActionPerformed(evt);
        }
    });

    btnCustomer.setText("Customer");
    btnCustomer.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCustomerActionPerformed(evt);
        }
    });

    btnVendor.setText("Vendor");
    btnVendor.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnVendorActionPerformed(evt);
        }
    });

    btnRunner.setText("Runner");
    btnRunner.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRunnerActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(22, 22, 22)
                            .addComponent(txtSearchUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSearch))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCustomer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnVendor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRunner)))
                    .addGap(0, 108, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(txtSearchUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSearch))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCustomer)
                .addComponent(btnVendor)
                .addComponent(btnRunner))
            .addGap(3, 3, 3)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String userID = txtSearchUserID.getText();
        //Set up a TableRowSorter
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) tblReadUser.getModel());
        tblReadUser.setRowSorter(sorter);
        
        RowFilter<DefaultTableModel, Object> rf = null;
        try {
            rf = RowFilter.regexFilter("^" + userID + "$", 0);
        } catch (java.util.regex.PatternSyntaxException e) {
            return;
        }
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        resetTable();
        String role = "customer";
        addToTable(role);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendorActionPerformed
        resetTable();
        String role = "vendor";
        addToTable(role);
    }//GEN-LAST:event_btnVendorActionPerformed

    private void btnRunnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunnerActionPerformed
        resetTable();
        String role = "runner";
        addToTable(role);
    }//GEN-LAST:event_btnRunnerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnRunner;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnVendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReadUser;
    private javax.swing.JTextField txtSearchUserID;
    // End of variables declaration//GEN-END:variables
}
